/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubscribersRouteImport } from './routes/subscribers'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LikedVideosRouteImport } from './routes/liked-videos'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WatchVideoIdRouteImport } from './routes/watch.$videoId'
import { Route as ProfileIdRouteImport } from './routes/profile.$id'
import { Route as CUsernameRouteImport } from './routes/c.$username'

const SubscribersRoute = SubscribersRouteImport.update({
  id: '/subscribers',
  path: '/subscribers',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LikedVideosRoute = LikedVideosRouteImport.update({
  id: '/liked-videos',
  path: '/liked-videos',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchVideoIdRoute = WatchVideoIdRouteImport.update({
  id: '/watch/$videoId',
  path: '/watch/$videoId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIdRoute = ProfileIdRouteImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CUsernameRoute = CUsernameRouteImport.update({
  id: '/c/$username',
  path: '/c/$username',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/liked-videos': typeof LikedVideosRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/subscribers': typeof SubscribersRoute
  '/c/$username': typeof CUsernameRoute
  '/profile/$id': typeof ProfileIdRoute
  '/watch/$videoId': typeof WatchVideoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/liked-videos': typeof LikedVideosRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/subscribers': typeof SubscribersRoute
  '/c/$username': typeof CUsernameRoute
  '/profile/$id': typeof ProfileIdRoute
  '/watch/$videoId': typeof WatchVideoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/liked-videos': typeof LikedVideosRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/subscribers': typeof SubscribersRoute
  '/c/$username': typeof CUsernameRoute
  '/profile/$id': typeof ProfileIdRoute
  '/watch/$videoId': typeof WatchVideoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collections'
    | '/dashboard'
    | '/history'
    | '/liked-videos'
    | '/login'
    | '/signup'
    | '/subscribers'
    | '/c/$username'
    | '/profile/$id'
    | '/watch/$videoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/collections'
    | '/dashboard'
    | '/history'
    | '/liked-videos'
    | '/login'
    | '/signup'
    | '/subscribers'
    | '/c/$username'
    | '/profile/$id'
    | '/watch/$videoId'
  id:
    | '__root__'
    | '/'
    | '/collections'
    | '/dashboard'
    | '/history'
    | '/liked-videos'
    | '/login'
    | '/signup'
    | '/subscribers'
    | '/c/$username'
    | '/profile/$id'
    | '/watch/$videoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectionsRoute: typeof CollectionsRoute
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRoute
  LikedVideosRoute: typeof LikedVideosRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  SubscribersRoute: typeof SubscribersRoute
  CUsernameRoute: typeof CUsernameRoute
  ProfileIdRoute: typeof ProfileIdRoute
  WatchVideoIdRoute: typeof WatchVideoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subscribers': {
      id: '/subscribers'
      path: '/subscribers'
      fullPath: '/subscribers'
      preLoaderRoute: typeof SubscribersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/liked-videos': {
      id: '/liked-videos'
      path: '/liked-videos'
      fullPath: '/liked-videos'
      preLoaderRoute: typeof LikedVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$videoId': {
      id: '/watch/$videoId'
      path: '/watch/$videoId'
      fullPath: '/watch/$videoId'
      preLoaderRoute: typeof WatchVideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$id': {
      id: '/profile/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof ProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$username': {
      id: '/c/$username'
      path: '/c/$username'
      fullPath: '/c/$username'
      preLoaderRoute: typeof CUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectionsRoute: CollectionsRoute,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRoute,
  LikedVideosRoute: LikedVideosRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  SubscribersRoute: SubscribersRoute,
  CUsernameRoute: CUsernameRoute,
  ProfileIdRoute: ProfileIdRoute,
  WatchVideoIdRoute: WatchVideoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
